version: '3.7'

services:
  flaskapp:
    container_name: flaskapp
    build: .
    volumes:
      - './:/app'
    ports:
      - 5001:5000
    networks:
      - sh-network
    depends_on:
      - neo4j

  neo4j:
    container_name: 'neo4j'
    image: neo4j:4.4.15-enterprise
    environment:
      - NEO4J_AUTH=neo4j/sh-1234
      - NEO4JLABS_PLUGINS=["graph-data-science"]
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - EXTENSION_SCRIPT= /entrypoint.sh
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j-data:/data
    networks:
      - sh-network
  

networks:
  sh-network:
    external: true
